config/routes.rb
Rails.application.routes.draw do
  devise_for :agents
  resources :friends
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/agent.rb
class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :agent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_agent!, except: %i[index show]
  before_action :correct_agent, only: %i[destroy edit update]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_agent.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_agent.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # Identify the correct agent
  def correct_agent
    @friend = current_agent.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: 'Not authorised to complete this action' if @friend.nil?
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:First_name, :Last_name, :Email, :Phone, :twitter, :agent_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :First_name, style: "display: block" %>
    <%= form.text_field :First_name %>
  </div>

  <div>
    <%= form.label :Last_name, style: "display: block" %>
    <%= form.text_field :Last_name %>
  </div>

  <div>
    <%= form.label :Email, style: "display: block" %>
    <%= form.text_field :Email %>
  </div>

  <div>
    <%= form.label :Phone, style: "display: block" %>
    <%= form.text_field :Phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.number_field :agent_id, id: :friend_agent_id, value: current_agent.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  
    <td>
      
      <%= friend.First_name %>
    </td>

    <td>
      
      <%= friend.Last_name %>
    </td>

    <td>
      
      <%= friend.Email %>
    </td>

    <td>
      
      <%= friend.Phone %>
    </td>

    <td>
      
      <%= friend.twitter %>
    </td>

    <td>
      
      <%= friend.agent_id %>
    </td>

    <td>
      <%= link_to "Show this friend", friend, class: "btn btn-info" %>
    </td>
    


</tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<h1>Friends List</h1>

<table class="table table-responsive table-hover" >
  <thead class="me">
    <td>First Name</td>
    <td>Last Name</td>
    <td>Email</td>
    <td>Phone</td>
    <td> Twitter</td>
    <td>User id</>
    <td>Show Friend</td>
  </thead>
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      
    </p>
  <% end %>
</table>

<button type="button" class="btn btn-warning">
  <%= link_to "New friend", new_friend_path %>
</button>

app/views/friends/new.html.erb
<h1>
  WE ADD FRIENDS HERE
</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<table>
  <tr>
    <%= render @friend %>
  </tr>
  
  
</table>

<div class="display-flex">
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: 'btn btn-warning'%><br/>
  <br/>
  <br/>
  <%= link_to "Back to friends", friends_path, class: 'btn btn-primary' %>
  <br/>

  <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-warning">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Rails YouTube Tutorial</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        

        <li class="nav-item">
          <%= link_to 'Home', home_index_path, class: "nav-link active" %>
        </li>

        <li>
          <%= link_to 'Friends_list', friends_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: 'nav-link' %>
        </li>

        <% if agent_signed_in? %>

          

          <li>
            <%= link_to 'Edit Profile', edit_agent_registration_path, class: 'nav-link' %>
          </li>

          <li>
            <%= link_to 'Add Friend', new_friend_path, class: 'nav-link' %>
          </li>

          <li>
            <%= link_to 'Sign out', destroy_agent_session_path, method: :DELETE, class: 'nav-link' %>
          </li>

        <% else %>

          <li>
            <%= link_to 'Sign in', new_agent_session_path, class: 'nav-link' %>
          </li>

          <li>
            <%= link_to 'Sign Up', new_agent_registration_path, class: 'nav-link' %>
          </li>

        <% end %>

        

        

        

        

        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Yeeey!</h1>

app/views/home/index.html.erb
<p>This is bladifkng</p>

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>


<div class="alert alert-success d-flex align-items-center mobutu" role="alert">
  <svg class="bi flex-shrink-0 me-2 mobutu-1" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    <%= notice %>
  </div>
</div>


</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RailsYoutubeTutorial</title>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    


  </head>
  <body class="main">
    <%= render 'home/header' %>
    
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>